# Generated by Django 4.1.3 on 2025-05-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("levelupapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Game_Type",
            new_name="GameType",
        ),
    ]
